apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  generation: 1
  labels:
    machineconfiguration.openshift.io/role: master
  name: 00-master-avahi
spec:
  config:
    ignition:
      version: 2.2.0
    systemd:
      units:
        - contents: |
            [Unit]
            Description=mDNS announcing with Avahi
            Wants=network-online.target
            After=network-online.target
            ConditionPathExists=!/etc/avahi/.avahi.done

            [Service]
            WorkingDirectory=/etc/avahi
            ExecStart=/usr/local/bin/avahi.sh

            Restart=on-failure
            RestartSec=5

            [Install]
            WantedBy=multi-user.target
          enabled: true
          name: avahi.service
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBzdGFuZGFsb25lPSdubyc/PjwhLS0qLW54bWwtKi0tPgo8IURPQ1RZUEUgc2VydmljZS1ncm91cCBTWVNURU0gImF2YWhpLXNlcnZpY2UuZHRkIj4KCjxzZXJ2aWNlLWdyb3VwPgogIDxuYW1lPkV0Y2RTUlY8L25hbWU+CiAgPHNlcnZpY2U+CiAgICA8dHlwZT5fZXRjZC1zZXJ2ZXItc3NsLl90Y3A8L3R5cGU+CiAgICA8cG9ydD4yMzgwPC9wb3J0PgogIDwvc2VydmljZT4KPC9zZXJ2aWNlLWdyb3VwPgo=
          verification: {}
        filesystem: root
        mode: 664
        path: /etc/avahi/services/etcd.service
      - contents:
          source: data:text/plain;charset=utf-8;base64,W1NFUlZFUl0KaG9zdC1uYW1lPSR7U0hPUlRfSE9TVE5BTUV9CmVuYWJsZS1kYnVzPW5vCg==
          verification: {}
        filesystem: root
        mode: 664
        path: /etc/avahi/avahi-daemon.conf.template
      - contents:
          source: data:text/plain;charset=utf-8;base64,IyEvdXNyL2Jpbi9lbnYgYmFzaApzZXQgLWUKCm1rZGlyIC0tcGFyZW50cyAvZXRjL2F2YWhpClNIT1JUX0hPU1ROQU1FPSIkKGhvc3RuYW1lIC1zKSIgZW52c3Vic3QgPCAvZXRjL2F2YWhpL2F2YWhpLWRhZW1vbi5jb25mLnRlbXBsYXRlID4gL2V0Yy9hdmFoaS9hdmFoaS1kYWVtb24uY29uZgoKQVZBSElfSU1BR0U9cXVheS5pby9jZWxlYmRvci9hdmFoaTpmMjkKaWYgISBwb2RtYW4gaW5zcGVjdCAiJEFWQUhJX0lNQUdFIiAmPi9kZXYvbnVsbDsgdGhlbgogICAgKD4mMiBlY2hvICJQdWxsaW5nIGF2YWhpIHJlbGVhc2UgaW1hZ2UuLi4iKQogICAgcG9kbWFuIHB1bGwgIiRBVkFISV9JTUFHRSIKZmkKCnBvZG1hbiBydW4gXAogICAgICAgIC0tcm0gXAogICAgICAgIC0tdm9sdW1lIC9ldGMvYXZhaGk6L2V0Yy9hdmFoaTp6IFwKICAgICAgICAtLW5ldHdvcms9aG9zdCBcCiAgICAgICAgIiR7QVZBSElfSU1BR0V9IgoKIyBXb3JrYXJvdW5kIGZvciBodHRwczovL2dpdGh1Yi5jb20vb3BlbmNvbnRhaW5lcnMvcnVuYy9wdWxsLzE4MDcKdG91Y2ggL2V0Yy9hdmFoaS8uYXZhaGkuZG9uZQoK
          verification: {}
        filesystem: root
        mode: 775
        path: /usr/local/bin/avahi.sh
