apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  generation: 1
  labels:
    machineconfiguration.openshift.io/role: master
  name: 00-master-keepalived
spec:
  config:
    ignition:
      version: 2.2.0
    systemd:
      units:
        - contents: |
            [Unit]
            Description=Manage node VIPs with keepalived
            Wants=network-online.target
            After=network-online.target
            ConditionPathExists=!/etc/keepalived/.keepalived.done

            [Service]
            WorkingDirectory=/etc/keepalived
            Environment=API_VIP=192.168.111.5
            ExecStart=/usr/local/bin/keepalived.sh

            Restart=on-failure
            RestartSec=5

            [Install]
            WantedBy=multi-user.target
          enabled: true
          name: keepalived.service
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,ZXhlYyBjdXJsIC1vIC9kZXYvbnVsbCAta0xzICJodHRwczovLzA6NjQ0My9oZWFsdGh6Igo=
          verification: {}
        filesystem: root
        mode: 775
        path: /etc/keepalived/check_ocp_api.sh
      - contents:
          source: data:text/plain;charset=utf-8;base64,dnJycF9zY3JpcHQgY2hrX29jcCB7CiAgICBzY3JpcHQgIi9ldGMva2VlcGFsaXZlZC9jaGVja19vY3BfYXBpLnNoIgogICAgaW50ZXJ2YWwgMQogICAgd2VpZ2h0IDUwCn0KdnJycF9pbnN0YW5jZSBWSV8xIHsKICAgIHN0YXRlIEJBQ0tVUAogICAgaW50ZXJmYWNlICR7SU5URVJGQUNFfQogICAgdmlydHVhbF9yb3V0ZXJfaWQgNTEKICAgIHByaW9yaXR5IDQwCiAgICBhZHZlcnRfaW50IDEKICAgIGF1dGhlbnRpY2F0aW9uIHsKICAgICAgICBhdXRoX3R5cGUgUEFTUwogICAgICAgIGF1dGhfcGFzcyBjbHVzdGVyX3V1aWRfbWFzdGVyX3ZpcAogICAgfQogICAgdmlydHVhbF9pcGFkZHJlc3MgewogICAgICAgICR7QVBJX1ZJUH0KICAgIH0KICAgIHRyYWNrX3NjcmlwdCB7CiAgICAgICAgY2hrX29jcAogICAgfQp9Cg==
          verification: {}
        filesystem: root
        mode: 664
        path: /etc/keepalived/keepalived.conf.template
      - contents:
          source: data:text/plain;charset=utf-8;base64,IyEvdXNyL2Jpbi9lbnYgYmFzaApzZXQgLWUKCmZ1bmN0aW9uIGdldF9pZmFjZV9pbl92aXBfc3VibmV0KCkgewogICAgbG9jYWwgdmlwCiAgICBsb2NhbCBuZXRfY2lkcgogICAgbG9jYWwgaWZhY2VfY2lkcnMKCiAgICB2aXA9IiQxIgoKICAgIGlmYWNlX2NpZHJzPSQoaXAgYWRkciBzaG93IHwgZ3JlcCAtdiAic2NvcGUgaG9zdCIgfCBncmVwIC1QbyAnaW5ldCBcS1tcZC5dKy9bXGQuXSsnIHwgeGFyZ3MpCiAgICBuZXRfY2lkcj0kKC91c3IvYmluL2VudiBweXRob24gLSAiJHZpcCIgIiRpZmFjZV9jaWRycyIgPDwgRU9GCmltcG9ydCBzeXMKaW1wb3J0IHNvY2tldAppbXBvcnQgc3RydWN0Cgp2aXAgPSBzeXMuYXJndlsxXQppZmFjZV9jaWRycyA9IHN5cy5hcmd2WzJdLnNwbGl0KCkKdmlwX2ludCA9IHN0cnVjdC51bnBhY2soIiFJIiwgc29ja2V0LmluZXRfYXRvbih2aXApKVswXQoKZm9yIGlmYWNlX2NpZHIgaW4gaWZhY2VfY2lkcnM6CiAgICBpcCwgcHJlZml4ID0gaWZhY2VfY2lkci5zcGxpdCgnLycpCiAgICBpcF9pbnQgPSBzdHJ1Y3QudW5wYWNrKCIhSSIsIHNvY2tldC5pbmV0X2F0b24oaXApKVswXQogICAgcHJlZml4X2ludCA9IGludChwcmVmaXgpCiAgICBtYXNrID0gaW50KCcxJyAqIHByZWZpeF9pbnQgKyAnMCcgKiAoMzIgLSBwcmVmaXhfaW50KSwgMikKICAgIHN1Ym5ldF9pcF9pbnRfbWluID0gaXBfaW50ICYgbWFzawogICAgc3VibmV0X2lwID0gc29ja2V0LmluZXRfbnRvYShzdHJ1Y3QucGFjaygiIUkiLCBzdWJuZXRfaXBfaW50X21pbikpCiAgICBzdWJuZXRfaXBfaW50X21heCA9IHN1Ym5ldF9pcF9pbnRfbWluIHwgaW50KCcxJyAqICgzMiAtIHByZWZpeF9pbnQpLCAyKQogICAgc3VibmV0X2lwX21heCA9IHNvY2tldC5pbmV0X250b2Eoc3RydWN0LnBhY2soIiFJIiwgc3VibmV0X2lwX2ludF9tYXgpKQogICAgc3lzLnN0ZGVyci53cml0ZSgnSXMgJXMgYmV0d2VlbiAlcyBhbmQgJXNcbicgJSAodmlwLCBzdWJuZXRfaXAsIHN1Ym5ldF9pcF9tYXgpKQogICAgaWYgc3VibmV0X2lwX2ludF9taW4gPCB2aXBfaW50IDwgc3VibmV0X2lwX2ludF9tYXg6CiAgICAgICAgc3VibmV0X2lwID0gc29ja2V0LmluZXRfbnRvYShzdHJ1Y3QucGFjaygiIUkiLCBzdWJuZXRfaXBfaW50X21pbikpCiAgICAgICAgcHJpbnQoJyVzLyVzJyAlIChzdWJuZXRfaXAsIHByZWZpeCkpCiAgICAgICAgc3lzLmV4aXQoMCkKc3lzLmV4aXQoMSkKRU9GCikKICAgIGlwIC1vIGFkZHIgc2hvdyB0byAiJG5ldF9jaWRyIiB8IGF3ayAne3ByaW50ICQyfScKfQoKbWtkaXIgLS1wYXJlbnRzIC9ldGMva2VlcGFsaXZlZAoKS0VFUEFMSVZFRF9JTUFHRT1yZWdpc3RyeS5hY2Nlc3MucmVkaGF0LmNvbS9yaG9zcDE0L29wZW5zdGFjay1rZWVwYWxpdmVkOjE0LjAKaWYgISBwb2RtYW4gaW5zcGVjdCAiJEtFRVBBTElWRURfSU1BR0UiICY+L2Rldi9udWxsOyB0aGVuCiAgICBlY2hvICJQdWxsaW5nIHJlbGVhc2UgaW1hZ2UuLi4iCiAgICBwb2RtYW4gcHVsbCAiJEtFRVBBTElWRURfSU1BR0UiCmZpCgpleHBvcnQgSU5URVJGQUNFPSIkKGdldF9pZmFjZV9pbl92aXBfc3VibmV0ICIkQVBJX1ZJUCIpIgpleHBvcnQgQVBJX1ZJUD0iJEFQSV9WSVAiCmVudnN1YnN0IDwgL2V0Yy9rZWVwYWxpdmVkL2tlZXBhbGl2ZWQuY29uZi50ZW1wbGF0ZSB8IHN1ZG8gdGVlIC9ldGMva2VlcGFsaXZlZC9rZWVwYWxpdmVkLmNvbmYKCnBvZG1hbiBydW4gXAogICAgICAgIC0tcm0gXAogICAgICAgIC0tdm9sdW1lIC9ldGMva2VlcGFsaXZlZDovZXRjL2tlZXBhbGl2ZWQ6eiBcCiAgICAgICAgLS1uZXR3b3JrPWhvc3QgXAogICAgICAgIC0tY2FwLWFkZD1ORVRfQURNSU4gXAogICAgICAgICIke0tFRVBBTElWRURfSU1BR0V9IiBcCiAgICAgICAgL3Vzci9zYmluL2tlZXBhbGl2ZWQgLWYgL2V0Yy9rZWVwYWxpdmVkL2tlZXBhbGl2ZWQuY29uZiAtLWRvbnQtZm9yayAtRCAtbCAtUAoKIyBXb3JrYXJvdW5kIGZvciBodHRwczovL2dpdGh1Yi5jb20vb3BlbmNvbnRhaW5lcnMvcnVuYy9wdWxsLzE4MDcKdG91Y2ggL2V0Yy9rZWVwYWxpdmVkLy5rZWVwYWxpdmVkLmRvbmUK
          verification: {}
        filesystem: root
        mode: 775
        path: /usr/local/bin/keepalived.sh
