apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  generation: 1
  labels:
    machineconfiguration.openshift.io/role: master
  name: 00-master-password
spec:
  config:
    ignition:
      version: 2.2.0
    passwd:
      users:
      - name: core
        passwordHash:
        - $6$2Cy8WeZ7uGbJ4qEv$vS8zP0HvbhtOTfu72JMoYIxm3Zb5T2880.vjwr9jug57uvwjuWmSJzjw9mUjgdTL4QSG2dvDpGaKJLHY741d./
