apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  generation: 1
  labels:
    machineconfiguration.openshift.io/role: master
  name: 00-master-remove-nic
spec:
  config:
    ignition:
      version: 2.2.0
    systemd:
      units:
        - contents: |
            [Unit]
            Description=Delete provisioning nic from the kernel command line so it can't stall dracut networking
            [Service]
            Type=oneshot
            ExecStart=/usr/local/bin/rm-provision-nic.sh
            [Install]
            WantedBy=multi-user.target
          enabled: true
          name: rm-provision-nic.service
    storage:
      files:
      - contents:
          verification: {}
        filesystem: root
        mode: 0755
        path: /usr/local/bin/rm-provision-nic.sh
